# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-12 13:19
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180511_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='slug', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to=blog.models.upload_location),
        ),
    ]
