# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-15 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180612_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 15, 18, 27, 498492, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
