# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-15 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180615_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='project',
            name='publish',
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 6, 15, 15, 20, 59, 587617, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
