# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_project_on_going'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
