# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-31 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseWork_title', models.CharField(blank=True, max_length=100)),
                ('courseWork_date', models.DateField()),
                ('courseWork_file', models.FileField(upload_to='coarse_work')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=35)),
                ('module_id', models.CharField(max_length=10)),
                ('module_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='coursework',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.Module'),
        ),
    ]
