# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-31 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100)),
                ('folder_path', models.CharField(max_length=100)),
                ('number_of_files', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_folder_name', models.CharField(max_length=100)),
                ('sub_folder_path', models.CharField(max_length=100)),
                ('sub_folder_files', models.IntegerField(default=0)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.Folder')),
                ('sub_folder', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.SubFolder')),
            ],
        ),
        migrations.RemoveField(
            model_name='coursework',
            name='module',
        ),
        migrations.DeleteModel(
            name='courseWork',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
